version: '3.3'

services:

  web:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/redmine.conf:/etc/nginx/conf.d/default.conf
      - ./data/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    networks:
      - net1

  redmine:
    image: redmine:5.0.2
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /opt/beget/redmine/data:/usr/src/redmine/files
      - /root/redmine-theme-yh:/usr/src/redmine/public/themes/redmine-theme-yh
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: $PASSWORD
      REDMINE_SECRET_KEY_BASE: supersecretkey
#    depends_on:
#      - db
    networks:
      - net1

  db:
    image: mysql:5.7.29
    restart: always
    volumes:
      - /opt/beget/redmine/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_ROOT_PASSWORD: $PASSWORD
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    networks:
      - net1

networks:
  net1:
    driver: bridge
